config/routes.rb
Rails.application.routes.draw do
  resources :photo_details
  root to: 'index#main'
  post 'file_upload', to: 'photo_details#upload'

end

app/models/photo_detail.rb
class PhotoDetail < ActiveRecord::Base
    
    def self.photo (year=2010)
        
        return PhotoDetail.where("strftime('%Y',date_taken) >= ?", year.to_s)

    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
    def main
       @photos = PhotoDetail.photo
       gon.photos = @photos
    end
end

app/controllers/photo_details_controller.rb
require 'date'

class PhotoDetailsController < ApplicationController
  before_action :set_photo_detail, only: [:show, :edit, :update, :destroy]

  # GET /photo_details
  # GET /photo_details.json
  def index
    @photo_details = PhotoDetail.all
  end

  # GET /photo_details/1
  # GET /photo_details/1.json
  def show
  end

  # GET /photo_details/new
  def new
    @pic_url = params[:p]
    logger.debug "the the the #{@pic_url}"
    @photo_detail = PhotoDetail.new
  end

  # GET /photo_details/1/edit
  def edit
  end

  # POST /photo_details
  # POST /photo_details.json
  def create
    start_date = Date.civil(params[:date_taken]["(1i)"].to_i,
                         params[:date_taken]["(2i)"].to_i,
                         params[:date_taken]["(3i)"].to_i)

    @photo_detail = PhotoDetail.new(title: params[:title], date_taken: start_date, place_taken: params[:place], link: '/uploads/'+session[:filename], story: params[:details])

    respond_to do |format|
      if @photo_detail.save
        format.html { 
          flash[:notice] = "Post successfully created"
          redirect_to new_photo_detail_path
        }
        format.json { render :show, status: :created, location: @photo_detail }
      else
        format.html { render :new }
        format.json { render json: @photo_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photo_details/1
  # PATCH/PUT /photo_details/1.json
  def update
    respond_to do |format|
      if @photo_detail.update(photo_detail_params)
        format.html { redirect_to new_photo_detail_path, notice: 'Photo detail was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo_detail }
      else
        format.html { render :edit }
        format.json { render json: @photo_detail.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photo_details/1
  # DELETE /photo_details/1.json
  def destroy
    @photo_detail.destroy
    respond_to do |format|
      format.html { redirect_to photo_details_url, notice: 'Photo detail was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  #User Defined Functions
  def upload
    uploaded_io = params[:picture_upload]
    
    if uploaded_io.nil?
      redirect_to new_photo_detail_path,notice: 'Please select a Photo.'
    else
      file_name = DateTime.now.strftime('%Y-%m-%d:%H:%M:%S') +'_image.png'
      file_path = Rails.root.join('public', 'uploads', file_name)
      image = MiniMagick::Image.open(uploaded_io.tempfile.path)
      #image.path #=> "/var/folders/k7/6zx6dx6x7ys3rv3srh0nyfj00000gn/T/magick20140921-75881-1yho3zc.jpg"
      image.resize "500x500"
      image.format "png"
      image.write file_path
      session[:filename] = file_name
      
      #file_name = DateTime.now.strftime('%Y-%m-%d:%H:%M:%S') + '_'+uploaded_io.original_filename
      #File.open(Rails.root.join('public', 'uploads', file_name), 'wb') do |file|
      #  session[:filename] = file_name
      #  file.write(uploaded_io.read)
      #end
      redirect_to new_photo_detail_path(:p => session[:filename])
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_photo_detail
      @photo_detail = PhotoDetail.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def photo_detail_params
      params.require(:photo_detail).permit(:title, :date_taken, :place, :link, :details)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/photo_details_helper.rb
module PhotoDetailsHelper
end

app/views/index/main.html.erb
<% require 'date' %>
<div class="well well-sm" style="background: linear-gradient(45deg, #cceeff, #e6f7ff);">
  <div class="row" style="display:flex;">
    <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
          <input type="range" id="year-range" class="form-control" name="points" min="2010" max="<%= Date.today.year %>" step="1" value="2010" onchange="populateYear(this)">
    </div>
    <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4">
      <input type="text" name="year-value" disabled value="2010"><span><small><i> Use slider to change year</i></small></span>
    </div>
  </div>
</div>

<%= debug @photos %>
<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="false" style="background: linear-gradient(45deg, #ffe0cc, #ffffff);">
  
  <!-- Wrapper for slides -->
  <div class="carousel-inner" role="listbox">

    <% @photos.to_a.each_with_index do |photo,index| %>
      <div class="item <%= index == 0? 'active':nil %>" style="margin:auto;">
        <img class="img-responsive center-block" src="<%=photo['link']  %>" height="500" width="500" >
      </div>
    <% end %>
  </div>

  <!-- Left and right controls -->
  <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<br/>
<div class="jumbotron" id="story-board" style="background: linear-gradient(45deg, #ffb3b3, #ffcccc);">
  <h4 class="text-center text-uppercase" id="photo-title">Center aligned text.</h4>
  <p class="lead" id="photo-story">There was a brown fox. Brown Fox was brown in color, hence it didnt appear black. so what happened is it jumped.</p>
  <p class="text-left" id="photo-location">Location,</p>
  <p class="text-left" id="photo-date">Date</p>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>The Journey</title>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js'></script>
  <script src='https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/4.0.0-alpha.6/js/bootstrap.min.js'></script>
  <%= include_gon %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  

</head>
<body style="background: radial-gradient(#f9ecf2, #f9ecf2, #f9ecf2);">
<div class="container-fluid">
  <header style="background-color:black;">
    <div class="row" style="display:flex;">
      <div class="col-xs-12 col-sm-12 col-md-8 col-lg-8">
        <a href="<%= root_path %>"><h3>The Journey <small>..down the memory lane</small></h3></a>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-4 col-lg-4" style="margin:auto;">
        <a class="btn btn-info" id="add-memories" href="<%= new_photo_detail_path %>" >Add memories</a>
      </div>
    </div>
  </header>
 <br/>
  <% flash.each do |key, value| %>
    <div class="alert alert-info"><%= value %></div>
  <% end %>
  <%= yield %>
</div>

</body>
</html>

app/views/photo_details/_form.html.erb
  
    <div class="row" style="display:flex">
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 jumbotron">
        <%= form_tag nil,multipart: true do  %>
          <div class="input-group absolute-center" >
            <span class="input-group-btn">
              <button type="submit" class="btn btn-default" id="file-upload" formaction="/file_upload"><span class="glyphicon glyphicon-upload"></span></button>
            </span>
            <input type="file" name='picture_upload' id='picture_upload' class="form-control" placeholder="Upload Photo">
          </div>
          <div>
            <% if pic_url != nil %>
              <img id="pic-upload" src="<%= ('/uploads/'+pic_url) %>">
            <%end%>
          </div>
        <%end%>
      </div>
      <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 jumbotron">
        <%= form_tag '/photo_details' do  %>
          <div class="field form-group">
            <%= label_tag :title %><br>
            <%= text_field_tag :title,nil,class: 'form-control', placeholder: 'Title of photo' %>
          </div>
          <div class="field form-group">
            <%= label_tag :date_taken %><br>
            <%= date_select :date_taken,nil,start_year:2009,use_two_digit_numbers: true, class: 'form-control' %>
          </div>
          <div class="field form-group">
            <%= label_tag :place %><br>
            <%= text_field_tag :place,nil, class: 'form-control', placeholder: 'Place photo was taken' %>
          </div>
        
          <div class="field form-group">
            <%= label_tag :details %><br>
            <%= text_area :details,nil,class: 'form-control', placeholder: 'Story' %>
          </div>
          <div class="actions">
            <%= submit_tag :Save, class: "btn btn-primary" %>
          </div>
        </div>
      <% end %>
    </div>
  

app/views/photo_details/edit.html.erb
<h1>Editing Photo Detail</h1>

<%= render 'form' %>

<%= link_to 'Show', @photo_detail %> |
<%= link_to 'Back', photo_details_path %>

app/views/photo_details/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Photo Details</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Place taken</th>
      <th>Date taken</th>
      <th>Link</th>
      <th>Story</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @photo_details.each do |photo_detail| %>
      <tr>
        <td><%= photo_detail.title %></td>
        <td><%= photo_detail.place_taken %></td>
        <td><%= photo_detail.date_taken %></td>
        <td><%= photo_detail.link %></td>
        <td><%= photo_detail.story %></td>
        <td><%= link_to 'Show', photo_detail %></td>
        <td><%= link_to 'Edit', edit_photo_detail_path(photo_detail) %></td>
        <td><%= link_to 'Destroy', photo_detail, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Photo detail', new_photo_detail_path %>

app/views/photo_details/new.html.erb
<div class="modal fade" tabindex="-1" role="dialog" data-backdrop="static" data-keyboard="false">
    <div class="modal-dialog">
    
      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Enter Credentials</h4>
        </div>
        <div class="modal-body">
          <form>
            <div class="form-group">
              <input type="email" class="form-control" id="user-name" placeholder="User Name">
            </div>
            <div class="form-group">
              <input type="password" class="form-control" id="password" placeholder="Password">
            </div>
          </form>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" id="submit" data-dismiss="modal">Submit</button>
        </div>
      </div>
      
    </div>
</div>


<%= render 'form', pic_url: @pic_url %>

<%= link_to 'Back', root_path,class:'btn btn-info' %>

app/views/photo_details/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @photo_detail.title %>
</p>

<p>
  <strong>Place taken:</strong>
  <%= @photo_detail.place_taken %>
</p>

<p>
  <strong>Date taken:</strong>
  <%= @photo_detail.date_taken %>
</p>

<p>
  <strong>Link:</strong>
  <%= @photo_detail.link %>
</p>

<p>
  <strong>Story:</strong>
  <%= @photo_detail.story %>
</p>

<%= link_to 'Edit', edit_photo_detail_path(@photo_detail) %> |
<%= link_to 'Back', photo_details_path %>